### ISSUE TITLE
insertion d'une alert JS dans l'inptu recherche

### ISSUE THREAD

**Issue by titineo** [Jeremy3wa/Chihuaworld#13]
insertion d'une alert JS dans l'input recherche: undefined index

**Comment by Shadownest** [comment]
Toujours dans la recherche :
http://192.168.1.95/dev/eshop/Chihuaworld/index.php?page=result&mot=%22%27&recherche=
( ! ) Warning: mysqli_fetch_object() expects parameter 1 to be mysqli_result, boolean given in /home/was1/sites/dev/eshop/Chihuaworld/apps/result.php on line 16
