### ISSUE TITLE
[Manager] Différents soucis

### ISSUE THREAD

**Issue by Shadownest** [Jeremy3wa/Chihuaworld#2]
ItemManager.class.php
- [x] Dans save(), y'a deux ; pour le $name à la fin de la ligne
- [x] Dans save(), quand vous récupérez le $id_category, la ligne est fausse
- [x] Dans save(), quand vous récupérez le $price, la ligne est fausse
- [x] Dans create(), pas le droit de faire un setIdCategory(), il faut utiliser setCategory()
- [x] Dans create(), pour le $name, y'a deux ; à la fin de la ligne
- [x] Dans create(), pour le $id_category, la ligne est fausse
- [x] Dans create(), pour le $price, la ligne est fausse

ReviewManager.class.php
- [x] Dans findByItem(), ce que vous récupérez via mysqli_fetch_object n'est PAS un $item, mais un $review !
- [x] Dans findById(), kiffe kiffe, vous êtes dans ReviewManager, vous ne pouvez récupérer que des reviews !

UserManager.class.php
- [x] Dans save(), vous utilisez getAdmin() au lieu de isAdmin()

CommandManager.class.php
- [x] Dans Status(), depuis quand on utilise le PascalCase pour le nom des méthodes... ?
- [x] Dans Status(), tout est faux...
- [x] Dans save(), a quoi correspond getIdStatus() ?
- [x] Dans create(), pas le droit d'utiliser setIdCustomer(), mais le remplacer par setCustomer()
- [x] Dans create(), wtf getIdStatus() encore ?

**Comment by Jeremy3wa** [comment]
On a corrigé la plupart, mais on sèche pas mal sur le Status...

**Comment by Twister1one** [comment]
Correction à 90% fini
Sinon on a corrigé la plupart, mais on sèche pas mal sur le **Status**...

Voici le code du Status 

---------------------------------------------------------------------------------------------------------


public function status(Command $status)
	{
		$status = mysqli_real_escape_string($command->getStatus());
		$res = mysqli_query($this->db, "SELECT * FROM command WHERE status='".$status."' ORDER BY date DESC");
		$command = mysqli_fetch_object($res, "Command", [$this->db]);
		
	}

---------------------------------------------------------------------------------------------------------------
